In [1]:
import numpy as np
from scipy.special import factorial
import pandas as pd

/home/lucas/.anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/lucas/.anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

In [2]:
def combinatorio(N, R):
    n = factorial(N)
    r = factorial(R)
    t = factorial((N - R))
    
    return int(n / (r*t))

In [103]:
combinatorio(20+1+(2*1), 20)

1771

In [4]:
def somatorio(k, valor_um, valor_dois):
    soma = 0
    for i in range(k):
        soma += combinatorio(valor_um, valor_dois)
    return soma

In [135]:
def calculo_combinatorio_simplex(r, variacao, iteracao):
    
    s = 1
    k = 0
    j = 1
    funcao_um = 0
    funcao_dois = 0
    funcao_tres = 0
    funcao_quatro = 0
    maximo = 0
    
    erres = []
    esses = []
    kas = []
    maximos = []
    valor_um = []
    valor_dois = []
    valor_tres = []
    valor_quatro = []
    
    while(j <= variacao):
        # Função que é constante, dependendo somente de r
        funcao_um = combinatorio(3*r -2, r)
        funcao_quatro = k*(2*r-1)
        
        # Função que varia com base em k
        funcao_tres = k * combinatorio(2*r -1, r)
        
        # Função que é somatório com base em k
        valor_da_funcao = 0
        i = 0
        funcao_dois = 0
        while(i <= k):
            funcao_dois += combinatorio((r+s+(2*i)), r)
            i+=1
        valor_da_funcao += funcao_dois
        
        # Valor Maximo
        maximo = np.max([funcao_dois, funcao_tres, funcao_quatro])
        
        # Salva os dados
        if(funcao_um > maximo):
            maximos.append(1)
        else:
            maximos.append(0)
        erres.append(r)
        esses.append(s)
        kas.append(k)
        valor_um.append(funcao_um)
        valor_dois.append(valor_da_funcao)
        valor_tres.append(funcao_tres)
        valor_quatro.append(funcao_quatro)
        
        # Iteração
        j += 1

        # Auxilio da iteração
        if(k == iteracao):
            k = 0
            if(s == 2):
                s = 1
                if(r == 1):
                    r += 4
                else:
                    r += 5
            else:
                s += 1
        else:
            k += 1
        
    
    # Dados para DataFrame e Excel
    frame = pd.DataFrame()
    frame["r"] = erres
    frame["s"] = esses
    frame["k"] = kas
    frame["1: (3r-2, r)"] = valor_um
    frame["2: SUM((r+s+2i, r))"] = valor_dois
    frame["3: k(2r-1, r)"] = valor_tres
    frame["4: k(2r-1)"] = valor_quatro
    frame["Maior: 1 > max(2, 3, 4)"] = maximos
     
    
    return frame

In [143]:
df = calculo_combinatorio_simplex(10, 252, 20)

In [144]:
df

,r,s,k,"1: (3r-2, r)","2: SUM((r+s+2i, r))","3: k(2r-1, r)",4: k(2r-1),"Maior: 1 > max(2, 3, 4)"
0,10,1,0,13123109,11,0,0,1
1,10,1,1,13123109,297,92378,19,1
2,10,1,2,13123109,3300,184756,38,1
3,10,1,3,13123109,22748,277134,57,1
4,10,1,4,13123109,115126,369512,76,1
5,10,1,5,13123109,467842,461890,95,1
6,10,1,6,13123109,1611908,554268,114,1
7,10,1,7,13123109,4880667,646646,133,1
8,10,1,8,13123109,13316952,739024,152,0
9,10,1,9,13123109,33346961,831402,171,0
10,10,1,10,13123109,77699126,923780,190,0
11,10,1,11,13123109,170260166,1016158,209,0
12,10,1,12,13123109,353839562,1108536,228,0
13,10,1,13,13123109,702169698,1200914,247,0
14,10,1,14,13123109,1337915094,1293292,266,0
15,10,1,15,13123109,2459014502,1385670,285,0
16,10,1,16,13123109,4376349284,1478048,304,0
17,10,1,17,13123109,7566536569,1570426,323,0
18,10,1,18,13123109,12744603320,1662804,342,0
19,10,1,19,13123109,20962425856,1755182,361,0
20,10,1,20,13123109,33740137725,1847560,380,0
21,10,2,0,13123109,66,0,0,1
22,10,2,1,13123109,1067,92378,19,1
23,10,2,2,13123109,9075,184756,38,1
24,10,2,3,13123109,52833,277134,57,1
25,10,2,4,13123109,237589,369512,76,1
26,10,2,5,13123109,884235,461890,95,1
27,10,2,6,13123109,2845491,554268,114,1
28,10,2,7,13123109,8157226,646646,133,1
29,10,2,8,13123109,21280335,739024,152,0
...,...,...,...,...,...,...,...,...
222,35,1,12,3864309224767426962877579264,62269484203367008,673117666899976814592,828,1
223,35,1,13,3864309224767426962877579264,341962057449676992,729210805808308215808,897,1
224,35,1,14,3864309224767426962877579264,1730780352189974464,785303944716639617024,966,1
225,35,1,15,3864309224767426962877579264,8137264744056507328,841397083624971018240,1035,1
226,35,1,16,3864309224767426962877579264,35777362177147354048,897490222533302419456,1104,1
227,35,1,17,3864309224767426962877579264,147963639993810140096,953583361441633820672,1173,1
228,35,1,18,3864309224767426962877579264,578516381884786457536,1009676500349965221888,1242,1
229,35,1,19,3864309224767426962877579264,2147913083433405955008,1065769639258296623104,1311,1
230,35,1,20,3864309224767426962877579264,7602523570523118549952,1121862778166628024320,1380,1
231,35,2,0,3864309224767426962877579264,665,0,0,1
232,35,2,1,3864309224767426962877579264,82915,56093138908331401216,69,1
233,35,2,2,3864309224767426962877579264,4579303,112186277816662802432,138,1
234,35,2,3,3864309224767426962877579264,149587815,168279416724994203648,207,1
235,35,2,4,3864309224767426962877579264,3339775100,224372555633325604864,276,1
236,35,2,5,3864309224767426962877579264,55591175950,280465694541657006080,345,1
237,35,2,6,3864309224767426962877579264,730840048485,336558833449988407296,414,1
238,35,2,7,3864309224767426962877579264,7905359319179,392651972358319808512,483,1
239,35,2,8,3864309224767426962877579264,72522925038248,448745111266651209728,552,1
240,35,2,9,3864309224767426962877579264,577560215000452,504838250174982610944,621,1
241,35,2,10,3864309224767426962877579264,4066908763830231,560931389083314012160,690,1
242,35,2,11,3864309224767426962877579264,25698341253133683,617024527991645413376,759,1
243,35,2,12,3864309224767426962877579264,147499945731365411,673117666899976814592,828,1
244,35,2,13,3864309224767426962877579264,776808235535562915,729210805808308215808,897,1
245,35,2,14,3864309224767426962877579264,3785914540806207651,785303944716639617024,966,1
246,35,2,15,3864309224767426962877579264,17199491236276760739,841397083624971018240,1035,1
247,35,2,16,3864309224767426962877579264,73292630144608161955,897490222533302419456,1104,1
248,35,2,17,3864309224767426962877579264,294548900283026559139,953583361441633820672,1173,1
249,35,2,18,3864309224767426962877579264,1121663378126217859235,1009676500349965221888,1242,1
250,35,2,19,3864309224767426962877579264,4064282193529878270115,1065769639258296623104,1311,1
251,35,2,20,3864309224767426962877579264,14064401419861016629411,1121862778166628024320,1380,1

In [145]:
df.to_excel("TabelaComparacao.xlsx")